version: "3.9"

services:
  web:
    build: .
    container_name: innovest-web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/innovest
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: innovest-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: innovest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
